language: android

jdk:
  - oraclejdk8

env:
    global:
        - NDK_VERSION=r12b
        - NDK_CCACHE=ccache
        - ANDROID_NDK_HOME=$HOME/.android/android-ndk-${NDK_VERSION}
        - SBTPATH=$HOME/.sbt
        - PATH=${ANDROID_NDK_HOME}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}

scala:
    - 2.11.8

before_cache:
    - find $HOME/.sbt -name "*.lock" | xargs rm
    - find $HOME/.ivy2 -name "*.lock" | xargs rm

cache:
    directories:
        - $HOME/.ivy2
        - $HOME/.sbt

android:
    components:
        - tools
        - build-tools-25.0.2
        - extra-android-m2repository

install:
    - >
      if [ ! -d "$ANDROID_NDK_HOME" ]; then
          mkdir -p $ANDROID_NDK_HOME;
          pushd $HOME/.android;
          export ARCH=`uname -m`;
          wget -q http://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux-${ARCH}.zip;
          unzip -q android-ndk-${NDK_VERSION}-linux-${ARCH}.zip;
          popd;
      fi
    - >
      if [ ! -f "$SBTPATH/sbt" ]; then
          pushd $SBTPATH;
          wget -q https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt;
          chmod a+x sbt;
          popd;
      fi

script:
    - $SBTPATH/sbt android:package

before_deploy:
      - git config --global user.name "xianren78"
      - git config --global user.email "qgtxqj@gmail.com"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
      - find $HOME/ -name "obfs-local-debug.apk" -exec mv {} $HOME/ \;
deploy:
  provider: releases
  api_key:
    secure: "AA/BQ3hG4xEueXkrFQmWK1BZvjVLlQpmlGNOBvG5QyLHGrpyr5x7YeVtlJKOY0tqYZbrHtooJK1oHGKVn9kgprD6cVokzI8IT5MORIv3raaFQV85uSY1w0EcGZ5IBIX10TptbQe+vLFReEVVwN3kdop1D6E4G7/7KjzjgN9wh1Yns7XsK0gPkTBp/xt4uqp+J/TnBKu5jkl89pQY+S15MmA+Jha+R9Fyupw27QRDvFG5FebMvczsoWR5GdN17rdddC1sN2B+LFJzB4xxcMkNV67SMy6+vkABWoD/u36+rzPBbY5rPTUFPw39pY1EHTmupQTravLESa/11Xf/jSwa+oSG3deHazGTXinPH70au3/T1BA0iEvEn5/VSteWuOAb/ttPE/KuUFtSy4VY7+YuYCP8ITO8vr5uj1e4KWKyzm2N+tdYXIozhkSDNlynd9xC10cXD0xEOueaTCb5Sp3whi5HO8891qxK8hYwrRLeVvUUiqzfmCquMivQAxNcXTH3v+dBOoZ/GVDVsXM084p3i2P4qVZjOj8ZPMuczmZjz6DFp8W2GsmUHCCr7R8khewZgqpX0cw3XHm7qZdrCrJZGKUy1BkQGwwlKK2h/TEsq0I2ddwLl+/Bg4D4UK9AlB8Jwl0soc5AbHwL6FmOBUpGWjo49ZlyZziVhG15p6PKj7Y="
  file: "$HOME/obfs-local-debug.apk"
  skip_cleanup: true
