language: android

jdk:
  - oraclejdk8

env:
    global:
        - NDK_VERSION=r12b
        - NDK_CCACHE=ccache
        - ANDROID_NDK_HOME=$HOME/.android/android-ndk-${NDK_VERSION}
        - SBTPATH=$HOME/.sbt
        - PATH=${ANDROID_NDK_HOME}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}

scala:
    - 2.11.8

before_cache:
    - find $HOME/.sbt -name "*.lock" | xargs rm
    - find $HOME/.ivy2 -name "*.lock" | xargs rm

cache:
    directories:
        - $HOME/.ivy2
        - $HOME/.sbt

android:
    components:
        - tools
        - build-tools-25.0.2
        - extra-android-m2repository

install:
    - >
      if [ ! -d "$ANDROID_NDK_HOME" ]; then
          mkdir -p $ANDROID_NDK_HOME;
          pushd $HOME/.android;
          export ARCH=`uname -m`;
          wget -q http://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux-${ARCH}.zip;
          unzip -q android-ndk-${NDK_VERSION}-linux-${ARCH}.zip;
          popd;
      fi
    - >
      if [ ! -f "$SBTPATH/sbt" ]; then
          pushd $SBTPATH;
          wget -q https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt;
          chmod a+x sbt;
          popd;
      fi

script:
    - $SBTPATH/sbt android:package

before_deploy:
      - git config --global user.name "xianren78"
      - git config --global user.email "qgtxqj@gmail.com"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
      - find $HOME/ -name "obfs-local-debug.apk" -exec mv {} $HOME/ \;
deploy:
  provider: releases
  api_key:
    secure: "fupe+XWMRkUKG2BibYAlkyUIpXQ6boKhic/yVbTb81BN4Is331KTIUy0YrSxfIdlatXqUNpN4X7sCDSwOdb50Yo31X3rbdQq7WsVBkKoOpf1v12fXPgTsfZX7KS5lmu2H20aTkrM18nc3SiZJ5M3tZSAAfgNlSvgmWkgJ3K3c6w4edUPfJgFZ9eNR+Y4UEfglrPw6ZlffolMJlQx2pVf/EXWTbi3Mtp2K2g2tqyAg7ntuJzyeSNQHm+YCOmQHNYm4ftSyCHrILLtl3TE3brqhOdtUbJLNc0D4dCEnsN7KmrxdTOctAWd7lmBhEhoS+bzXsTU1EHsaI+cdH1lR8k5hL30FxlbhYhDfgKl8p9dRqb7gE8ObgKgrqBI4Bhw7E22w8TZsmgremgfq9cfPlggJGbbZdf2FtsvaProbYEZa2iOR3utUeW7Mt6sdEHr+KirHExrOGSHbktUdKw6KE09GkcKN0IP0wkPY6L9IG2GDktqsJDRemdIVaiB6NovtJ9Ov6FCdjgWK5H6Tr37blwxaVApymXSCcv0hWhA3TOFPaX2WZ359Ev9E9iY+uS72J8D112iW25o7OaMs7gNEaiEfOQgAcL5xd2s6KZBGujAeYu2tKd+ZsxcWKEsscDsVNe1Hs7dT2QBX7nXc069LW0YWcZ/xGRKRnQgvtdE78l+xUo="
  file: "$HOME/obfs-local-debug.apk"
  skip_cleanup: true
